name: Secrets and Variables

on:
    workflow_dispatch:

jobs:
    prod:
        environment: prod
        runs-on: ubuntu-24.04
        env:
            REPO_SECRET: ${{secrets.REPO_SECRET}}
            REPO_VAR: ${{vars.REPO_VAR}}
            ENVIRONMENT_SECRET: ${{secrets.SECRET}}
            ENVIRONMENT_VAR: ${{vars.VAR}}
        steps:
            - run: |
                  echo "REPO_SECRET: $REPO_SECRET"
                  echo "REPO_VAR: $REPO_VAR"
                  echo "ENVIRONMENT_SECRET: $ENVIRONMENT_SECRET"
                  echo "ENVIRONMENT_VAR: $ENVIRONMENT_VAR"
